/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// Support both Figma Make (hardcoded) and Vercel (env vars)
export const projectId = import.meta.env?.VITE_SUPABASE_URL 
  ? new URL(import.meta.env.VITE_SUPABASE_URL).hostname.split('.')[0]
  : "ljljxfgvjhrcocjruzgh";

export const publicAnonKey = import.meta.env?.VITE_SUPABASE_ANON_KEY 
  || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxqbGp4Zmd2amhyY29janJ1emdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc2OTU2MTIsImV4cCI6MjA4MzI3MTYxMn0.8gzVTy6V89vB8SpK0y9L5Dg9M24phvipHWjfRU69jjo";